# Generated by Django 5.2.5 on 2025-10-29 14:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Insurance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "insurance_provider",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("cnss", "CNSS"),
                            ("cnops", "CNOPS"),
                            ("axa", "AXA"),
                            ("saham", "Saham"),
                            ("", "—"),
                        ],
                        default="",
                        max_length=20,
                        verbose_name="Fournisseur d'assurance",
                    ),
                ),
                (
                    "insurance_policy_number",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="Numéro de police"
                    ),
                ),
                (
                    "coverage_type",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="Type de couverture"
                    ),
                ),
                (
                    "expiration_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date d'expiration"
                    ),
                ),
                (
                    "holder_name",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="Titulaire"
                    ),
                ),
                ("insurance_notes", models.TextField(blank=True, verbose_name="Notes")),
            ],
            options={
                "verbose_name": "Assurance",
                "verbose_name_plural": "Assurances",
            },
        ),
        migrations.CreateModel(
            name="InterventionType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, unique=True, verbose_name="Nom"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
            ],
            options={
                "verbose_name": "Type d’intervention",
                "verbose_name_plural": "Types d’interventions",
            },
        ),
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=120, verbose_name="Prénom")),
                (
                    "last_name",
                    models.CharField(max_length=120, verbose_name="Nom de famille"),
                ),
                (
                    "birth_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date de naissance"
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("male", "Homme"),
                            ("female", "Femme"),
                            ("other", "Autre"),
                            ("", "Non précisé"),
                        ],
                        default="",
                        max_length=10,
                        verbose_name="Genre",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Téléphone"
                    ),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Adresse"
                    ),
                ),
                (
                    "city",
                    models.CharField(blank=True, max_length=120, verbose_name="Ville"),
                ),
                (
                    "postal_code",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="Code postal"
                    ),
                ),
            ],
            options={
                "verbose_name": "Patient",
                "verbose_name_plural": "Patients",
            },
        ),
        migrations.CreateModel(
            name="SecretaryReferral",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("patient", models.CharField(max_length=100)),
                ("medecin", models.CharField(max_length=100)),
                ("intervention", models.CharField(max_length=200)),
                ("date", models.DateTimeField()),
                ("assurance", models.CharField(max_length=50)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("En attente", "En attente"),
                            ("Confirmé", "Confirmé"),
                            ("Terminé", "Terminé"),
                            ("Annulé", "Annulé"),
                            ("À rappeler", "À rappeler"),
                        ],
                        default="En attente",
                        max_length=20,
                    ),
                ),
                (
                    "priorite",
                    models.CharField(
                        choices=[
                            ("Basse", "Basse"),
                            ("Normale", "Normale"),
                            ("Haute", "Haute"),
                            ("Urgente", "Urgente"),
                        ],
                        default="Normale",
                        max_length=20,
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=30, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("internalNotes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="UrgencyLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=50, unique=True, verbose_name="Nom"),
                ),
                (
                    "color",
                    models.CharField(
                        blank=True,
                        help_text="Ex : rouge, orange, vert",
                        max_length=20,
                        verbose_name="Couleur",
                    ),
                ),
                (
                    "priority",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Plus petit = plus urgent",
                        verbose_name="Priorité",
                    ),
                ),
            ],
            options={
                "verbose_name": "Niveau d’urgence",
                "verbose_name_plural": "Niveaux d’urgence",
                "ordering": ["priority"],
            },
        ),
        migrations.CreateModel(
            name="Referral",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "consultation_reason",
                    models.TextField(blank=True, verbose_name="Motif de consultation"),
                ),
                (
                    "medical_history",
                    models.TextField(blank=True, verbose_name="Antécédents médicaux"),
                ),
                (
                    "referring_doctor",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="Médecin référent"
                    ),
                ),
                (
                    "establishment",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="Établissement"
                    ),
                ),
                (
                    "room_number",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Numéro de chambre"
                    ),
                ),
                (
                    "physician",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="Médecin"
                    ),
                ),
                (
                    "target_specialty",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="Spécialité cible"
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, verbose_name="Notes supplémentaires"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "Nouveau"),
                            ("sent", "Envoyé"),
                            ("accepted", "Accepté"),
                            ("rejeté", "Rejeté"),
                            ("arrived", "Arrivé"),
                        ],
                        default="new",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Dernière mise à jour"
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="referrals",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Médecin créateur",
                    ),
                ),
                (
                    "insurance",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="referrals",
                        to="referrals.insurance",
                        verbose_name="Assurance",
                    ),
                ),
                (
                    "intervention_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="referrals",
                        to="referrals.interventiontype",
                        verbose_name="Type d’intervention",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referrals",
                        to="referrals.patient",
                        verbose_name="Patient",
                    ),
                ),
                (
                    "urgency_level",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="referrals",
                        to="referrals.urgencylevel",
                        verbose_name="Niveau d’urgence",
                    ),
                ),
            ],
            options={
                "verbose_name": "Référence",
                "verbose_name_plural": "Références",
                "ordering": ("-created_at",),
            },
        ),
    ]
