# Generated by Django 5.2.7 on 2025-11-05 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interventiontype',
            name='description',
        ),
        migrations.RemoveField(
            model_name='interventiontype',
            name='name',
        ),
        migrations.AddField(
            model_name='interventiontype',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interventiontype',
            name='description_fr',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='interventiontype',
            name='name_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='interventiontype',
            name='name_fr',
            field=models.CharField(default='Inconnu', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
