# Generated by Django 5.2.7 on 2025-11-05 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0002_remove_interventiontype_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urgencylevel',
            name='name',
        ),
        migrations.AddField(
            model_name='urgencylevel',
            name='name_en',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nom (anglais)'),
        ),
        migrations.AddField(
            model_name='urgencylevel',
            name='name_fr',
            field=models.CharField(default='default', max_length=50, unique=True, verbose_name='Nom (français)'),
            preserve_default=False,
        ),
    ]
