# Generated by Django 5.2.7 on 2025-11-05 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='specialite',
        ),
        migrations.AddField(
            model_name='user',
            name='specialite_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Spécialité (EN)'),
        ),
        migrations.AddField(
            model_name='user',
            name='specialite_fr',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Spécialité (FR)'),
        ),
    ]
