# Generated by Django 5.2.5 on 2025-08-18 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="code_personnel",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("DIRECTION", "Direction"),
                    ("SECRETAIRE", "Secrétaire"),
                    ("MEDECIN", "Médecin"),
                ],
                max_length=20,
            ),
        ),
    ]
