# Generated by Django 5.2.7 on 2025-11-06 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_specialite_user_specialite_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_fr', models.CharField(max_length=100, verbose_name='Nom (FR)')),
                ('name_en', models.CharField(max_length=100, verbose_name='Name (EN)')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Spécialité',
                'verbose_name_plural': 'Spécialités',
                'ordering': ['name_fr'],
            },
        ),
        migrations.RemoveField(
            model_name='user',
            name='specialite_en',
        ),
        migrations.RemoveField(
            model_name='user',
            name='specialite_fr',
        ),
        migrations.AddField(
            model_name='user',
            name='specialite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='accounts.specialty', verbose_name='Spécialité'),
        ),
    ]
