# Generated by Django 5.2.5 on 2025-08-22 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_user_code_personnel_alter_user_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="code_personnel",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
