# Generated by Django 5.2.7 on 2025-11-05 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='name',
        ),
        migrations.AddField(
            model_name='room',
            name='name_en',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Name (EN)'),
        ),
        migrations.AddField(
            model_name='room',
            name='name_fr',
            field=models.CharField(default='default', max_length=120, verbose_name='Nom (FR)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('available', 'Disponible / Available'), ('occupied', 'Occupée / Occupied'), ('cleaning', 'Nettoyage / Cleaning'), ('maintenance', 'Maintenance / Maintenance')], default='available', max_length=50),
        ),
    ]
