# Generated by Django 5.2.7 on 2025-11-05 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_remove_room_name_room_name_en_room_name_fr_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointmenttype',
            name='name',
        ),
        migrations.AddField(
            model_name='appointmenttype',
            name='name_en',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Name (EN)'),
        ),
        migrations.AddField(
            model_name='appointmenttype',
            name='name_fr',
            field=models.CharField(default='defalut', max_length=120, verbose_name='Nom (FR)'),
            preserve_default=False,
        ),
    ]
