# Generated by Django 5.2.7 on 2025-11-06 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_remove_appointmenttype_name_appointmenttype_name_en_and_more'),
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arrivalnotification',
            name='speciality',
        ),
        migrations.AddField(
            model_name='arrivalnotification',
            name='intervention_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='appointments.appointmenttype', verbose_name='Type d’intervention'),
        ),
    ]
